EXPERIMENT_DIR = config["experiment_dir"]
RUN_DIR = config["run_dir"]

################################################################################
# Getting Database Resources (Defining the Search Space)
################################################################################
# For the uniprot_proteome_id method the user provides proteome_ids.txt directly
# in EXPERIMENT_DIR/input/. A setup rule copies it into RUN_DIR so that all
# downstream rules can always read from RUN_DIR consistently.
# For all other methods proteome_ids.txt is generated by ncbi_taxonomy.smk into RUN_DIR.
if config["search_space_method"] == "uniprot_proteome_id":
    # Scope the localrule inside the conditional so Snakemake doesn't warn
    # about an undefined rule for the other methods.
    localrules: seed_proteome_ids

    rule seed_proteome_ids:
        input: os.path.join(EXPERIMENT_DIR, "input/proteome_ids.txt")
        output: os.path.join(RUN_DIR, "proteome_ids.txt")
        log: os.path.join(RUN_DIR, "logs/search_space/uniprot_proteome_ids/seed_proteome_ids.log")
        run:
            import shutil
            shutil.copy(input[0], output[0])

rule get_fasta_from_proteome_ids:
    input:
        proteome_id_input = os.path.join(RUN_DIR,"proteome_ids.txt")
    output:
        # File containing proteome ids. Allows user to see what proteomes for each organism were downloaded.
        # Also contains NA values for NCBI taxon ids that are not in the Uniprot database.
       proteome_id_output = os.path.join(RUN_DIR,"database_resources/proteome_ids.txt"),
       fasta_output = os.path.join(RUN_DIR,"database_resources/database.fasta")
    log: os.path.join(RUN_DIR,"logs/search_space/uniprot_proteome_ids/get_fasta_from_proteome_ids.log")
    container:
        config["containers"]["conduitr"]
    script:
        "scripts/get_fasta_from_proteome_ids.R"

# Generating Complete Taxonomy Information for Each Organism ID
#
# Note: Because of how UniProt organizes proteome identifiers, the exact NCBI strain ID
# provided by the user may not always correspond to the final proteome selected.
# For example, a given strain may:
#   - be marked as redundant with another strain,
#   - have a low-quality or incomplete proteome, or
#   - lack a dedicated proteome entirely, while its parent species has one.
#
# In addition, some user-supplied taxonomy IDs may not have any corresponding
# proteome available in UniProtKB. These entries are excluded from further analysis.
#
# As a result, the taxonomy associated with the selected proteome may differ slightly
# from the user-supplied taxonomy at the strain level. However, the species- or
# subspecies-level taxonomy will always remain consistent with the user input.
rule get_taxonomy:
    input:
        # File containing results of get fasta. Includes info about what taxa ids had cooresponding proteome ids.
        proteome_ids = os.path.join(RUN_DIR,"database_resources/proteome_ids.txt")
    output:
        taxonomy = os.path.join(RUN_DIR,"database_resources/taxonomy.txt")
    log: os.path.join(RUN_DIR,"logs/search_space/ncbi_taxonomy/get_taxonomy.log")
    container: config["containers"]["conduitr"]
    script:
      "scripts/get_taxonomy.R"

# Note: get_protein_info_from_fasta, plot_taxonomic_tree, and
# make_database_resources_readme are provided by database_processing.smk.
# All UniProt-based search-space methods include that module alongside this
# one via `use rule * from database_processing` in the main Snakefile.
