# ===============================
# Experiment and file configuration
# ===============================
# Name of the experiment (used to locate the correct experiment directory)
experiment: 
# Config file for generating DIA-NN spectral library (relative to main Snakefile)
generate_diann_spectral_library_config: config/generate_diann_spectral_library.cfg
# Config file for running DIA-NN search (relative to main Snakefile)
run_diann_config: config/run_diann.cfg
# Sample annotation file path (relative to experiment directory)
sample_annotation: input/sample_annotation.txt
# Output directory path (relative to experiment directory)
output_dir: output/
# ===============================
# Search space configuration
# ===============================
# Method to define the search space. Options:
# - "ncbi_taxonomy_id": Use NCBI taxonomy IDs
# - "uniprot_proteome_id": Use UniProt proteome IDs
# - "peptidotyping": First-pass search on species-specific peptides
# - "MAG": Use metagenome-assembled genomes
# - "metaphlan": Use MetaPhlAn profiling
# - "16S": Use 16S rRNA sequences
search_space_method: ncbi_taxonomy_id
# If using sequencing-based methods, the minimum relative abundance to include a species
relative_abundance_threshold: 0.01
# Optional: add an extra proteome ID (e.g., host reference)
# FALSE = None
# Examples: Human = UP000005640, Mouse C57/BL6 = UP000000589
append_additional_proteome_id: FALSE
# Optional: add an extra NCBI taxonomic ID (e.g., host species)
# FALSE = None
# Examples: Human = 9606, Mouse = 10090
append_additional_ncbi_taxa_id: FALSE
# ===============================
# Resource configuration. Allows the user to specify paths to any hefty resources if they already exist on system.
# If not, conduit will handle their download automatically if they are required by workflow user specifies.
# ===============================
# Annotation resources. 
eggnog_database: "resources/annotation/eggnog/e5.og_annotations.tsv" # ~200mb
# Resources for metaphlan strategy.
metaphlan_database_dir: "resources/metaphlan" # ~54 Gb
# Resources for peptidotyping strategy
unipept_sequences: "resources/databases/sequences.tsv.lz4" # ~ 1.46 Gb
unipept_taxons: "resources/databases/taxons.tsv.lz4"
# Resources needed for mags
bakta_database: "resources/bakta" # ~ 84 GB
# Might not need this depending on how we want to call MAGs.
gbtk_database: "resources/gbtk" # ~140 GB

