name: Snakemake dry-run tests

on:
  push:
    branches: [main, testing]
  pull_request:
    branches: [main]

jobs:
  dry-runs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.11"
          channels: conda-forge, bioconda
          channel-priority: strict
          activate-environment: snakemake
          environment-file: tests/envs/snakemake.yml

      - name: Run dry-run tests
        shell: bash -el {0}
        run: bash tests/run_dry_runs.sh
